PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
]

PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

PJT/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("read/<int:account_pk>", views.read, name="read"),
    path("alarm/<int:account_pk>/<int:routine_pk>", views.alarm, name="alarm"),
    path("delete/<int:account_pk>/<int:routine_pk>", views.delete, name="delete"),
    path("update/<int:routine_pk>", views.update, name="update"),
    path("days/<int:account_pk>", views.days, name="days"),
    path("detail/<int:account_pk>/<int:routine_pk>", views.detail, name="detail"),
    path("result/<int:account_pk>/<int:routine_pk>", views.result, name="result"),
]

PJT/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
    <title>danbi</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light text-bg-light p-0 p-lg-0">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'articles:index' %}">
                <img class="" src="{% static 'images/logo.png' %}" alt="logo" height="80">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4 fs-5 d-flex justify-content-between">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">내 정보</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input class="bg-light border-0 nav-link" type="submit" value="로그아웃">
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
    {% bootstrap_javascript %}
    <footer class="text-center py-2">
        <div class="container sticky-bottom">
            <p>Web-django wink assignment, by KP</p>
        </div>
    </footer>
</body>

</html>