PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
]

PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

PJT/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)


class UserManager(BaseUserManager):

    use_in_migrations = True

    def create_user(self, email, nickname, password):

        if not email:
            raise ValueError("이메일을 입력해주세요")
        if not password:
            raise ValueError("비밀번호를 입력해주세요")
        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname, password):

        user = self.create_user(
            email=self.normalize_email(email),
            nickname=nickname,
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserManager()
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    nickname = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "nickname",
    ]

    def __str__(self):
        return self.email

    def __str__(self):
        return self.nickname

    @property
    def is_staff(self):
        return self.is_admin

PJT/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from .models import User, UserManager
import string
from django.forms import ValidationError


def contains_special_charater(value):
    for char in value:
        if char in string.punctuation:
            return True
    return False


def contains_alnum(value):
    for char in value:
        if char.isalnum():
            return True
    return False


class UserCreationForm(forms.ModelForm):
    # 사용자 생성 폼
    email = forms.EmailField(
        label=_("Email"),
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Email address"),
                "required": "True",
            }
        ),
    )
    nickname = forms.CharField(
        label=_("닉네임"),
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("닉네임"),
                "required": "True",
            }
        ),
    )
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": _("비밀번호는 특수문자, 알파벳, 숫자를 포함해 8글자 이상으로 설정해주세요"),
                "required": "True",
            }
        ),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Password confirmation"),
                "required": "True",
            }
        ),
    )

    class Meta:
        model = User
        fields = ("email", "nickname")

    def clean_password2(self):
        # 두 비밀번호 입력 일치 확인
        # 비밀번호 특수문자 포함 확인
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if (
            len(password1) < 8
            or not contains_special_charater(password1)
            or not contains_alnum(password1)
        ):
            raise ValidationError("비밀번호는 8자이상, 특수문자와 알파벳 또는 숫자를 포함해야 합니다")
        if password1 and password2 and password1 != password2:
            raise ValidationError("패스워드가 일치하지 않습니다")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.email = UserManager.normalize_email(self.cleaned_data["email"])
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    # 비밀번호 변경 폼
    password = ReadOnlyPasswordHashField(label=_("Password"))

    class Meta:
        model = User
        fields = (
            "email",
            "nickname",
            "password",
            "is_active",
            "is_superuser",
        )

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

PJT/accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from .models import User

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            form.save()
            auth_login(request, user)
            return redirect("articles:index")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("articles:index")


@login_required
def profile(request, pk):
    user = User.objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/profile.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("articles:index")

PJT/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <h1 class="pb-3">password update</h1>
    <h3>email</h3>
    <h4>{{ user.email }}</h4>
    <hr>
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
</div>
{% endblock content %}

PJT/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <h1>Log in</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="login">
    </form>
</div>
{% endblock content %}

PJT/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container  py-5">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title mb-3">My profile</h3>
            <h4 class="card-subtitle my-3">이메일 : {{ user.email }}</h4>
            <h5 class="card-text">닉네임 : {{ user.nickname }}</h5>
        </div>
    </div>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary ms-3 my-3 end" href="{% url 'accounts:change_password' %}">change password</a>
        <a class="btn btn-primary ms-3 my-3 end" href="{% url 'accounts:delete' %}">Delete account</a>
    </div>
</div>

{% endblock content %}

PJT/accounts/templates/accounts/signup.html
<!-- accounts/signup.html -->
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <h1>회원 가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
</div>
{% endblock content %}