PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
]

PJT/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("read/<int:account_pk>", views.read, name="read"),
    path("alarm/<int:account_pk>/<int:routine_pk>", views.alarm, name="alarm"),
    path("delete/<int:account_pk>/<int:routine_pk>", views.delete, name="delete"),
    path("update/<int:routine_pk>", views.update, name="update"),
    path("days/<int:account_pk>", views.days, name="days"),
    path("detail/<int:account_pk>/<int:routine_pk>", views.detail, name="detail"),
    path("result/<int:account_pk>/<int:routine_pk>", views.result, name="result"),
]

PJT/articles/models.py
from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField

# Create your models here.


class Routines(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    MIRACLE = "miracle"
    HOMEWORK = "homework"
    category = models.CharField(
        max_length=9,
        choices=(
            (MIRACLE, "기상"),
            (HOMEWORK, "숙제"),
        ),
        default=MIRACLE,
    )
    goal = models.TextField()
    is_alarm = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class Routine_result(models.Model):
    routine = models.ForeignKey(Routines, on_delete=models.CASCADE)
    NOT = "not"
    TRY = "try"
    DONE = "done"
    PROGRESS = (
        (NOT, "안함"),
        (TRY, "시도"),
        (DONE, "완료"),
    )
    result = models.CharField(choices=PROGRESS, default=NOT, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class Routine_day(models.Model):
    MON = "Monday"
    TUE = "Tuesday"
    WED = "Wednesday"
    THU = "Thursday"
    FRI = "Friday"
    SAT = "Saturday"
    SUN = "Sunday"
    DAY_WEEK = (
        (MON, "Monday"),
        (TUE, "Tuesday"),
        (WED, "Wednesday"),
        (THU, "Thursday"),
        (FRI, "Friday"),
        (SAT, "Saturday"),
        (SUN, "Sunday"),
    )
    day = MultiSelectField(
        choices=DAY_WEEK,
        min_choices=1,
        max_choices=7,
    )
    routine = models.ForeignKey(Routines, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

PJT/articles/forms.py
from django.forms import ModelForm
from .models import Routines, Routine_result, Routine_day


class RoutineForm(ModelForm):
    class Meta:
        model = Routines
        fields = ("title", "category", "goal", "is_alarm")


class Routine_resultForm(ModelForm):
    class Meta:
        model = Routine_result
        fields = ("result",)


class Routine_dayForm(ModelForm):
    class Meta:
        model = Routine_day
        fields = ("day",)

PJT/articles/views.py
from django.shortcuts import redirect, render
from .models import Routine_day, Routine_result, Routines
from .forms import Routine_resultForm, RoutineForm, Routine_dayForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    routines = Routines.objects.all()
    context = {
        "routines": routines,
    }
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        routine_form = RoutineForm(request.POST)
        routine_day_form = Routine_dayForm(request.POST)
        if routine_form.is_valid():
            routine = routine_form.save(commit=False)
            routine.user = request.user
            routine.save()
            print(routine.pk)
            routine_result = Routine_result.objects.create(routine=routine)
            routine_result.save()
            routine_day = routine_day_form.save(commit=False)
            routine_day.routine = routine
            routine_day.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("articles:index")
    else:
        routine_form = RoutineForm()
        routine_day_form = Routine_dayForm()
    context = {
        "routine_form": routine_form,
        "routine_day_form": routine_day_form,
        "message": {
            "msg": "You have successfully created the routine.",
            "status": "ROUTINE_CREATE_OK",
        },
    }
    return render(request, "articles/form.html", context=context)


@login_required
def read(request, account_pk):
    routines = Routines.objects.filter(user_id=account_pk)
    routine_days = Routine_day.objects.all()
    context = {
        "routines": routines,
        "routine_days": routine_days,
    }
    return render(request, "articles/read.html", context)


@login_required
def alarm(request, account_pk, routine_pk):
    print(account_pk, routine_pk)
    routine = Routines.objects.get(pk=routine_pk)
    routine.is_alarm = not routine.is_alarm
    routine.save()
    return redirect("articles:detail", account_pk, routine_pk)


@login_required
def delete(request, account_pk, routine_pk):
    routine = Routines.objects.get(pk=routine_pk)
    routine.is_deleted = True
    routine.save()
    messages.success(request, "루틴 삭제가 완료되었습니다")
    return redirect("articles:days", account_pk)


@login_required
def update(request, routine_pk):
    routine = Routines.objects.get(pk=routine_pk)
    routine_day = Routine_day.objects.get(routine_id=routine_pk)
    if request.method == "POST":
        routine_form = RoutineForm(request.POST, request.FILES, instance=routine)
        routine_day_form = Routine_dayForm(
            request.POST, request.FILES, instance=routine_day
        )
        if routine_form.is_valid():
            routine_form.save()
            routine_day_form.save()
            messages.success(request, "글 수정이 완료되었습니다.")
            return redirect("articles:index")
    else:
        routine_form = RoutineForm(instance=routine)
        routine_day_form = Routine_dayForm(instance=routine_day)
    context = {
        "routine_form": routine_form,
        "routine_day_form": routine_day_form,
        "message": {
            "msg": "The routine has been modified.",
            "status": "ROUTINE_UPDATE_OK",
        },
    }
    return render(request, "articles/form.html", context)


from datetime import date
import calendar


@login_required
def days(request, account_pk):
    today = calendar.day_name[date.today().weekday()]
    routine_days = (
        Routine_day.objects.select_related("routine")
        .filter(day__contains=str(today))
        .filter(routine__user_id=account_pk)
    )
    context = {
        "routine_days": routine_days,
        "today": today,
        "message": {
            "msg": "Routine lookup was successful.",
            "status": "ROUTINE_LIST_OK",
        },
    }
    return render(request, "articles/days.html", context)


def detail(request, account_pk, routine_pk):
    routine = Routines.objects.get(pk=routine_pk)
    routine_day = Routine_day.objects.get(routine_id=routine_pk)
    routine_result = Routine_result.objects.get(routine_id=routine_pk)
    context = {
        "routine": routine,
        "routine_day": routine_day,
        "routine_result": routine_result,
    }
    return render(request, "articles/detail.html", context)


def result(request, account_pk, routine_pk):
    routine_result = Routine_result.objects.get(routine_id=routine_pk)
    if request.method == "POST":
        routine_resultform = Routine_resultForm(
            request.POST, request.FILES, instance=routine_result
        )
        if routine_resultform.is_valid():
            routine_resultform.save()
            messages.success(request, "결과 수정이 완료되었습니다")
            return redirect("articles:detail", account_pk, routine_pk)
    else:
        routine_resultform = Routine_resultForm(instance=routine_result)
    context = {
        "routine_resultform": routine_resultform,
    }
    return render(request, "articles/result.html", context)

PJT/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form routine_form %}
        <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="글쓰기">
        </div>
    </form>

</div>
{% endblock %}

PJT/articles/templates/articles/days.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container py-5">
    <h1 class="my-4">안녕하세요 {{ user }}님</h1>

    <div class="card m-5">
        <div class="card-header">
            <h2 class="card-title">{{ today }} 루틴</h2>
        </div>
        <div class="card-body">
            <h4 class="card-subtitle mb-4">기상 루틴</h4>
            {% for routine_day in routine_days %}
            {% if routine_day.routine.category == 'miracle' %}
            {% if not routine_day.routine.is_deleted %}
            <hr>
            <h5 class="card-text">제목 :
                <a href="{% url 'articles:detail' user.pk routine_day.routine.pk %}">
                    {{ routine_day.routine.title }}
                </a>
            </h5>
            <p class="card-text">내용 : {{ routine_day.routine.goal }}</p>
            {% endif %}
            {% endif %}
            {% endfor %}
        </div>
        <hr>
        <div class="card-body">
            <h4 class="card-subtitle mb-4">숙제 루틴</h4>
            {% for routine_day in routine_days %}
            {% if routine_day.routine.category == 'homework' %}
            {% if not routine_day.routine.is_deleted %}
            <hr>
            <h5 class="card-text">제목 :
                <a href="{% url 'articles:detail' user.pk routine_day.routine.pk %}">{{ routine_day.routine.title }}</a>
            </h5>
            <p class="card-text">내용 : {{ routine_day.routine.goal }}</p>
            {% endif %}
            {% endif %}
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

PJT/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container py-5">
    <div class="card m-5 p-3">
        <h1 class="my-4">안녕하세요 {{ user }}님</h1>
    </div>
    <div class="card m-5">
        <div class="card-body">
            <h3 class="card-title mb-3">{{ routine.title }}</h3>
            <hr>
            <p class="card-subtitle my-3">카테고리 : {{ routine.category }}</p>
            <hr>
            <p class="card-subtitle my-3">요일 :
                {{ routine_day.day }}
            </p>
            <hr>
            <h5 class="card-text">목표 : {{ routine.goal }}</h5>
            <hr>
            <p class="card-text">알람 설정 :
                {% if routine.is_alarm %}
                <a class="text-primary text-decoration-none" href="{% url 'articles:alarm' user.pk routine.pk %}">ON</a>
                {% else %}
                <a class="text-danger text-decoration-none" href="{% url 'articles:alarm' user.pk routine.pk %}">OFF</a>
                {% endif %}
            </p>
            {% if routine.created_at == routine.modified_at %}
            작성일 : {{ routine.created_at }}
            {% else %}
            작성일 : {{ routine.modified_at }} (수정됨)
            {% endif %}
            <p class="card-text">결과 :
                <a href="{% url 'articles:result' user.pk routine.pk %}">
                    {{ routine_result.result }}
                </a>

            </p>
            <a class="btn btn-primary" href="{% url 'articles:update' routine.pk %}">수정하기</a>
            <a class="btn btn-danger" href="{% url 'articles:delete' user.pk routine.pk %}">삭제하기</a>
        </div>
    </div>
</div>
{% endblock %}

PJT/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form routine_form %}
        <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="글쓰기">
        </div>
    </form>

</div>
{% endblock %}

PJT/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container text-center py-5">
    <img src="{% static 'images/background.jpg' %}">
    {% if request.user.is_authenticated %}
    <h1 class="my-4">안녕하세요 {{ user }}님</h1>
    <a class="btn btn-secondary" href="{% url 'articles:create' %}">루틴 만들기</a>
    <a class="btn btn-secondary" href="{% url 'articles:read' user.pk %}">모든 루틴 확인하기</a>
    <a class="btn btn-secondary" href="{% url 'articles:days' user.pk %}">오늘의 루틴</a>
    {% endif %}
</div>
{% endblock %}

PJT/articles/templates/articles/read.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container py-5">
    <div class="card m-5 p-3">
        <h1 class="my-4">안녕하세요 {{ user }}님</h1>
    </div>
    {% for routine in routines %}
    {% if not routine.is_delete and routine.user == user %}
    <div class="card m-5">
        <div class="card-body">
            <h3 class="card-title mb-3">{{ routine.title }}</h3>
            <hr>
            <p class="card-subtitle my-3">카테고리 : {{ routine.category }}</p>
            <hr>
            <h5 class="card-text">목표 : {{ routine.goal }}</h5>
            <hr>
            <p class="card-text">알람 설정 :
                {% if routine.is_alarm %}
                <a class="text-primary text-decoration-none" href="{% url 'articles:alarm' routine.pk %}">ON</a>
                {% else %}
                <a class="text-danger text-decoration-none" href="{% url 'articles:alarm' routine.pk %}">OFF</a>
                {% endif %}
            </p>
            {% if routine.created_at == routine.modified_at %}
            작성일 : {{ routine.created_at }}
            {% else %}
            작성일 : {{ routine.modified_at }} (수정됨)
            {% endif %}
            <p class="card-text"></p>
            <a class="btn btn-primary" href="{% url 'articles:update' routine.pk %}">수정하기</a>
            <a class="btn btn-danger" href="{% url 'articles:delete' routine.pk %}">삭제하기</a>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

PJT/articles/templates/articles/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form routine_resultform %}
        <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="제출">
        </div>
    </form>

</div>
{% endblock %}